### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by antonkulaga** [sjrd/scala-js-actors#2]
I think that in a long term webrtc support will be extremely useful. Webrtc now supports not only audio-video connections but also Data Channels http://www.webrtc.org/chrome#TOC-Data-Channels-  that allow to send data directly between clients. I think it opens a variety of opprotunities for scalajs actors than will be able not only to communicate with each other and server actors but also directly between browsers via webrts datachannels

**Comment by sjrd** [comment]
Closing as I'm about to [archive](https://help.github.com/articles/about-archiving-repositories/) this repository.
